name: "pos-elli-system"

services:
  db:
    image: postgres:15
    container_name: elli_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: elli_backend
    restart: always
    depends_on:
      - db
    env_file:
      - ./apps/backend/.env
    ports:
      - "${PORT}:${PORT}"
    command: ["yarn", "dev"]

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/pos-elli/Dockerfile
    container_name: elli_frontend
    restart: always
    env_file:
      - ./apps/frontend/pos-elli/.env
    ports:
      - "5173:5173"
    command: ["yarn", "dev"]

volumes:
  db_data:
